version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, eb)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.1.4
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    #  configure the pipeline so that only pushes to the main/master branch would trigger build
    filters:
      branches:
        only:
          - main
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: install UI dependencies
          command: |
            npm run frontend:install
      - run:
          name: install Server dependencies
          command: |
            npm run api:install
      - run:
          name: Run backend build
          command: |
            npm run api:build
      - run:
          name: Deploy frontend & back 
          command: |
            npm run deploy
        # set backend environment variables
      - run:
          name: set backend environment variables 
          command: |
            npm run api:set_env
