components:
    schemas:
        course:
            type: object
            properties:
                course_code:
                    type: string 
                course_name:
                    type: string



/courses/{course_code}:
  get:
    tags: 
        - Courses
    summary: This endpoint shows a detailed course description
    description: This endpoint shows a detailed course description
    parameters:
        - in: path
          name: course_code
          type: string
          required: true
    responses:
        200: 
            description: valid request
            content:
                application/json:
                    schema:
                        course:
                            $ref: '#components/schemas/instructor'

                    example:
                        course:
                            course_code: 'ECEN424'
                            course_name: 'INTRODUCTION TO DATABASE MANAGEMENT SYSTEMS'
  patch:
    tags: 
        - Courses
    summary: this endpoint is used to update courses
    description: this endpoint is used to update courses
    security:
        - BearerAuth: []
    parameters:
        - in: path
          name: course_code
          required: true
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object 
                    properties:
                      course:
                        $ref: '#components/schemas/course'
    responses:
        200:
            description: OK, course updated successfully
  delete:
    tags: 
        - Courses
    summary: this endpoint is used to delete courses
    description: this endpoint is used to delete courses
    security:
        - BearerAuth: []
    parameters:
        - in: path
          name: course_code
          required: true
    responses:
        200:
            description: OK, course deleted successfully



/courses:
  get:
    tags: 
        - Courses
    summary: this endpoint gets all the course
    description: the number of courses returned is dependent on the limit parameter
    parameters:
        - in: query
          name: pageNo
          type: integer
          required: true
        - in: query
          name: limit
          type: integer
          required: true
        - in: query
          name: q
          type: string
          required: false
          description: This parameter is used to search using course name or course code
    responses:
        200: 
            description: valid request
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            pagination:
                                types: object
                                properties:
                                    pagenNo: 
                                        type: number
                                    limit:
                                        type: number
                                    totalNumber:
                                        type: number
                            results:
                                type: array
                                items:
                                    $ref: '#components/schemas/course'
  post:
    tags: 
        - Courses
    summary: this endpoint is used to create new courses
    description: this endpoint is used to create new courses
    security:
        - BearerAuth: []
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object 
                    properties:
                      course:
                        $ref: '#components/schemas/course'
    responses:
        201:
            description: OK, course created successfully