components:
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
    schemas:
        student:
            type: object
            properties:
                student_username:
                    type: string
                f_name:
                    type: string
                m_name:
                    type: string
                l_name:
                    type: string
                student_faculty:
                    type: string
                    enum:
                        - EAS
                        - Business
                        - CS
                student_password:
                    type: string




/login:
  post:
    tags:
        - Student
    summary: this endpoint is used to log users in
    description: this endpoint is used to log users in
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object
                    properties:
                      student:
                        type: object
                        properties:
                          student_username:
                            type: string
                          student_password:
                            type: string
    responses:
        200:
            description: OK, user authenticated successfully
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            AccessToken:
                                type: string





/logout:
  post:
    tags:
        - Student
    summary: this endpoint is used to logout users in
    description: this endpoint is used to logout users in
    security:
        - BearerAuth: []
    responses:
        200:
            description: OK, Logged out successfully
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            msg:
                                type: string




/students/{student_username}:
  delete:
    tags:
        - Student
    summary: This endpoint is used to delete student account
    description: This endpoint is used to delete student account
    security:
        - BearerAuth: []
    parameters:
        - in: path
          name: student_username
          type: string
          required: true
    responses:
        200:
            description: OK, Student removed successfully
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            msg:
                                type: string


/students:
  post:
    tags:
        - Student
    summary: This endpoint is used to create new students
    description: This endpoint is used to create new students
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object
                    properties:
                      student:
                        $ref: '#components/schemas/student'
    responses:
        201:
            description: OK, student created successfully
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            AccessToken:
                                type: string