version: '3'

services:
  node-alpine:
    container_name: schedule_generator_api
  # su_node:
    build: 
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - db_default
    network_mode: db_default
    # volumes: 
    #   - .:/app
    environment:
      DB_HOST: schedule_generator_db
      DB_PORT: 3306
    # working_dir: /app 
    ports:
      - "3000:3000"
  #   depends_on: 
  #     - mysql-db
  # mysql-db:
  #   image: mysql:latest
  #   container_name: schedule_generator_db
  #   environment:
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: "@sdfghjkL12345"
  #     MYSQL_ROOT_PASSWORD: "@sdfghjkL12345"
  #     MYSQL_DATABASE: schedule_generator
  #   ports:
  #     - "3366:3306"
